baseURL = "https://abhitamrakar.github.io/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "AT"
    author = ""
    description = ""
    copyright = "abhishek.tamrakar"

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "light"
        showAttribute = false
        singlePage = false

    [params.favicons]
        use = false
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Abhishek Tamrakar"
		tagline = "AT"
		location = "Pune, MH"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://www.linkedin.com/in/abhishektamrakar/"
            title = "LinkedIn"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/abhiTamrakar"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "https://twitter.com/abhitamrakar1?lang=en"
            title = "Twitter"
		[[params.social.list]]
            class = "fas"
            icon = "fa-envelope"
            url = "mailto:abhishek.tamrakar08@gmail.com"
            title = "Google Scholar"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "**Effective Communicator, Team Player, Blogger**, with 11+ years of technical experience in implementations and configurations of distributed systems and micro-services architecture. Coming with advanced knowledge of Linux based operating systems and proficiency with majority of public cloud providers, along with understanding of DevOps practices and tool-sets to effectively create scalable and fault tolerant solutions."

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Senior DevOps Engineer"
            dates = "Dec 2018 - *Present*"
            company = "Qualys, Inc."
            details = """Responsible to create kubernetes based platform to provide resiliency, increase reliability of the application infrastructure and help application teams to reduce the time to delivery. 

* Created scalable kubernetes platform.
* Wrote E2E CD automation to setup kubernetes clusters using Terraform, Ansible and Hashicorp Vault.
* Automation to handle cluster upgrade without downtime.
* Designed and helped the team to implement necessary DevOps processes and best practices.
* Helped application teams to convert the legacy compose files to easily maintainable helm charts and to migrate to kubernetes.
* Helped Ops team to understand and troubleshoot issues over containerized  micro-services distributed over Docker Swarm and Kubernetes. 
* Created necessary documentation to help the team understand the platform and ease of troubleshooting.
* Wrote necessary Ansible modules wherever required.
* Wrote kubernetes plugins/scripts that can help in debugging issues easily.
* Wrote the automation to get the cluster capacity the way kubernetes sees it to help SRE and OPS understand the current cluster capacity to help with sizing/scaling of the cluster.
* Helped in implementation of FEDRAMP compliance for the platform and micro-services.
* Developed a process to rotate CA for kubernetes cluster with a minimal downtime and contributed same to the kubernetes documentation. ref [#19351](https://github.com/kubernetes/website/pull/19351)."""
        [[params.experience.list]]
            position = "Senior Team Lead"
            dates = "Dec 2017 - Dec 2018"
            link = "https://www.persistent.com/"
            company = "Persistent Systems"
            details = """* Mentored and helped team to understand and learn the key concepts.
* Wrote necessary documentation to help with troubleshooting and understanding of basic concepts within the scope of the projects.
* Followed DevOps practices to incorporate automation solutions to create complex infrastructure quickly and efficiently.
* Used Ansible, Terraform, Docker and Kubernetes over multiple clouds to create sustainable production infrastructure.
* Automation to handle implementation of control plane, data plane and a separate monitoring plane to create a stable application platform.
* POC of various open-source tools to keep up with the tool set in order to provide clients with cost effective and viable solutions.
* Wrote python module to handle concurrent read/write operations in MongoDB."""
        [[params.experience.list]]
            position = "Senior Cloud Automation Engineer"
            dates = "Aug 2016 - Nov 2017"
            company = "Rean Cloud"
            details = """* Use of Ansible playbooks, depending on client requirements
* Use of Chef Cookbooks, depending on client requirements.
* Use of Docker to create compact containers for applications and other dependent resources.
* Use of Inspec to write validation test cases for infrastructure and server resources.
* Use of Jenkins Orchestrator for delivery aspects.
* Deploying infrastructure with (AWS resources) ECS/EB and ECR.
* Use of Cloud formation templates/terraform wherever required to create complex AWS infrastructure to sustain the production level environment."""
        [[params.experience.list]]
            position = "Senior Systems Engineer"
            dates = "July 2013 - Aug 2016"
            company = "Hewlett Packard Enterprise"
            details = """* Configuration of FTP server, mail relay over TLS and SSL protocols. 
* Setting up routing and routing rules via iptables/firewall for enhanced security.
* SME for SSL certificates related requests and issues.
* Writing compact and efficient bash shell scripts to automate various tasks and reports.
* Scheduling, executing and validating technology changes following the Change Management process.
* Hands on exposure on source code management and versioning systems like GIT and SVN.
* Implemented SSL automation for web/ mail/ FTP applications to renew all SSL certificates automatically and handle troubleshooting SSL issues wherever possible via automated scripts. 
* Implemented FTP automation project for all types of FTP servers to automate all ftp account creation and troubleshooting FTP related issues."""
        [[params.experience.list]]
            position = "Technical Executive"
            dates = "April 2012 - July 2013"
            company = "NTT Data"
            details = """* Providing L2 support, troubleshooting and Configuration for Morgan Stanley Web Servers.
* Configuration and troubleshooting of F5/Big-IP Load Balancers. 
* Configuration, troubleshooting of Apache Tomcat servers and deploying application"""
        [[params.experience.list]]
            position = "Systems Officer"
            dates = "May 2009 - Jan 2012"
            company = "High Court of Madhya Pradesh, MP, India"
            details = """* Installation and Configuring RHEL System and Suse Linux Server.
* Automation of various tasks through Shell scripting
* Automated backups.
* Automated disk space and load issue resolution and root cause analysis.
* Automated configuration of lamp server.
* Installation via tar balls, rpm, apt, apk, dpkg depending upon distribution.
* Disk Management partitioning tools like fdisk, file system management ext3, and file system utilities (fsck, e2fsck, mke2fs, and dumpe2fs).
* Installation of DNS, DHCP server."""

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "BE in Electronics and Communication"
            college = "Rajiv Gandhi Technical University, Bhopal."
            dates = "2014 - 2018"

    # Publication section
    [params.publication]
        title = "Articles"
        icon = "fab fa-blogger"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Articles", "Proceedings"]

        [[params.publication.list]]
            title = "Troubleshoot kubernetes with the power of tmux and kubectl"
            authors = "Abhishek Tamrakar"
            date = "2019"
            link = "https://opensource.com/article/20/2/kubernetes-tmux-kubectl"
            type = "Articles"

        [[params.publication.list]]
            title = "Hone advanced bash skills by building Minesweeper"
            authors = "Abhishek Tamrakar"
            date = "2019"
            link = "https://opensource.com/article/19/9/advanced-bash-building-minesweeper"
            type = "Articles"
		
        [[params.publication.list]]
            title = "Gating production in DevOps"
            authors = "Abhishek Tamrakar"
            date = "2019"
            link = "https://opensource.com/article/19/5/gating-production-devops"
            type = "Articles"

        [[params.publication.list]]
            title = "Infrastructure Monitoring, Defence against surprise downtime"
            authors = "Abhishek Tamrakar"
            date = "2019"
            link = "https://opensource.com/article/19/2/infrastructure-monitoring"
            type = "Articles"

        [[params.publication.list]]
            title = "Infrastructure Security, SSL certificates and challenges"
            authors = "Abhishek Tamrakar"
            date = "2018"
            link = "https://medium.com/@abhishek.tamrakar/infrastructure-security-ssl-tls-certificates-and-challenges-9464d75a5e17"
            type = "Articles"

        [[params.publication.list]]
            title = "Building foundation for the infrastructure on cloud"
            authors = "Abhishek Tamrakar"
            date = "2018"
            link = "https://medium.com/faun/building-foundation-for-the-infrastructure-on-cloud-the-first-layer-a4f68c89cc14"
            type = "Articles"

        [[params.publication.list]]
            title = "implementing pessimistic locks in MongoDB"
            authors = "Abhishek Tamrakar"
            date = "2018"
            link = "https://medium.com/faun/implementing-pessimistic-locks-in-mongodb-8f3fbe2ddfa9"
            type = "Articles"

    # Project section
    [params.project]
        title = "Github Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "SSL-On-Demand"
            url = "https://github.com/abhiTamrakar/ssl-on-demand"
            description = "This utility predicts SSL certificate expiry and generated output i various formats including prometheus metrics."
        [[params.project.list]]
            title = "Kube-Plugins"
            url = "https://github.com/abhiTamrakar/kube-plugins"
            description = "The project contains scripts that can be used as kubernetes plugins to ease debugging issues in various phases of application deployment on kubernetes clusters."
        [[params.project.list]]
            title = "Kapct"
            url = "https://github.com/abhiTamrakar/kapct"
            description = "This utility calculates kubernetes cluster capacity the way cluster sees it."
        [[params.project.list]]
            title = "Playground"
            url = "https://github.com/abhiTamrakar/playground"
            description = "The project contains popular games written in bash and many more to come."

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Ansible, Terraform, Jenkins"
            skillrating = 95            
        [[params.skill.list]]
            skill = "Docker, Kubernetes"
            skillrating = 90
        [[params.skill.list]]
            skill = "Bash, Linux"
            skillrating = 90
        [[params.skill.list]]
            skill = "AWS Cloud, Azure Cloud"
            skillrating = 80
        [[params.skill.list]]
            skill = "Python"
            skillrating = 80
        [[params.skill.list]]
            skill = "Golang, Consul, Vault"
            skillrating = 65

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"
		
        [[params.hobby.list]]
		    hobby = "Listening to old bollywood songs"
        [[params.hobby.list]]
		    hobby = "Badminton"
        [[params.hobby.list]]
		    hobby = "Carrom"
        [[params.hobby.list]]
		    hobby = "Writing Poems, Ghazal"
        [[params.hobby.list]]
		    hobby = "Book Reading"
